version: "3"

services:

  nats:
    image: nats:latest
    expose:
      - "4222"
      - "4223"
    ports:
      - "8222:8222"
      - "8223:8223"
      - "4223:4223"
      - "4222:4222"
    network_mode: host

  factory:
    build: ./factory
    network_mode: host

  diller:
    build: ./dealer
    network_mode: host

  jvmdiller:
    build: ./jvmDealer
    network_mode: host
