// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package car

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Order) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type OrderAccepted struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderAccepted) Reset()         { *m = OrderAccepted{} }
func (m *OrderAccepted) String() string { return proto.CompactTextString(m) }
func (*OrderAccepted) ProtoMessage()    {}
func (*OrderAccepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *OrderAccepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderAccepted.Unmarshal(m, b)
}
func (m *OrderAccepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderAccepted.Marshal(b, m, deterministic)
}
func (m *OrderAccepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderAccepted.Merge(m, src)
}
func (m *OrderAccepted) XXX_Size() int {
	return xxx_messageInfo_OrderAccepted.Size(m)
}
func (m *OrderAccepted) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderAccepted.DiscardUnknown(m)
}

var xxx_messageInfo_OrderAccepted proto.InternalMessageInfo

func (m *OrderAccepted) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type Delivery struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delivery) Reset()         { *m = Delivery{} }
func (m *Delivery) String() string { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()    {}
func (*Delivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Delivery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delivery.Unmarshal(m, b)
}
func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delivery.Marshal(b, m, deterministic)
}
func (m *Delivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delivery.Merge(m, src)
}
func (m *Delivery) XXX_Size() int {
	return xxx_messageInfo_Delivery.Size(m)
}
func (m *Delivery) XXX_DiscardUnknown() {
	xxx_messageInfo_Delivery.DiscardUnknown(m)
}

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Delivery) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Delivery) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "car.Order")
	proto.RegisterType((*OrderAccepted)(nil), "car.OrderAccepted")
	proto.RegisterType((*Delivery)(nil), "car.Delivery")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x69, 0x4b, 0xab, 0x3d, 0xa8, 0x43, 0x10, 0xc9, 0x58, 0x3a, 0xd5, 0xc5, 0xc5, 0x27,
	0x10, 0x5c, 0x3a, 0x09, 0xc5, 0x17, 0x48, 0x73, 0x87, 0x44, 0x5a, 0x53, 0x92, 0x54, 0xf0, 0xed,
	0x25, 0xb1, 0x19, 0x1d, 0xbf, 0xe3, 0xe3, 0xe7, 0x3b, 0xa8, 0x26, 0xb2, 0x56, 0x3c, 0xe8, 0x34,
	0x1b, 0xed, 0x34, 0xcb, 0xa4, 0x30, 0x4d, 0x07, 0xf9, 0xcd, 0x20, 0x19, 0xb6, 0x83, 0x54, 0x21,
	0x4f, 0xea, 0xa4, 0x2d, 0xfb, 0x54, 0x21, 0x3b, 0x40, 0x21, 0x26, 0xbd, 0xbc, 0x1c, 0x4f, 0xeb,
	0xa4, 0xcd, 0xfb, 0x95, 0x18, 0x87, 0x8d, 0x5d, 0x86, 0x27, 0x49, 0xc7, 0xb3, 0x20, 0x47, 0x6c,
	0x8e, 0x50, 0x85, 0xa9, 0x8b, 0x94, 0x34, 0x3b, 0x42, 0xaf, 0x6a, 0x7f, 0xe8, 0xe2, 0x6e, 0xc4,
	0xe6, 0x0e, 0xdb, 0x2b, 0x8d, 0xea, 0x4d, 0xe6, 0xf3, 0xdf, 0x62, 0x7b, 0xc8, 0x27, 0x8d, 0x34,
	0x86, 0x82, 0xb2, 0xff, 0x81, 0xf7, 0x91, 0x9c, 0x50, 0xa3, 0x8d, 0x01, 0x2b, 0x0e, 0x45, 0xf8,
	0xeb, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x03, 0x51, 0xb8, 0xf8, 0xe8, 0x00, 0x00, 0x00,
}
